### ISSUE TITLE
Does not run when invoked via systemd

### ISSUE THREAD

**Issue by cschramm** [dotless-de/vagrant-vbguest#156]
I have a systemd service installed which runs `vagrant up` as root for a specific VM. Unfortunately it seems like the plugin is not invoked there and thus vagrant fails to mount the vboxsf if there had been an update. If I issue the `vagrant up` manually using sudo, it works fine. This is probably an issue with all plugins, not vbguest specifically, but I honestly don't know what could be missing in the systemd environment...

**Comment by gchaix** [comment]
I'm seeing this issue as well on CentOS 7.  The plugin is trying to call `/etc/init.d/vboxadd`, which no longer exists in the 5.0.6 (and possibly older) versions of the guest additions on systemd distributions:

```
bash: line 3: /etc/init.d/vboxadd: No such file or directory
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/etc/init.d/vboxadd setup

Stdout from the command:



Stderr from the command:

bash: line 3: /etc/init.d/vboxadd: No such file or directory
```

The service *does* get installed, but it's disabled:
```
[root@vagrant-multi1 vagrant]# service vboxadd status
Redirecting to /bin/systemctl status  vboxadd.service
vboxadd.service
   Loaded: loaded (/opt/VBoxGuestAdditions-5.0.6/init/vboxadd; disabled)
   Active: inactive (dead)
```

Enabling it and restarting the box (or just starting the service) fixes the issue:
```
[root@vagrant-multi1 vagrant]# systemctl enable vboxadd
ln -s '/usr/lib/systemd/system/vboxadd.service' '/etc/systemd/system/multi-user.target.wants/vboxadd.service'
[root@vagrant-multi1 vagrant]# service vboxadd status
Redirecting to /bin/systemctl status  vboxadd.service
vboxadd.service
   Loaded: loaded (/opt/VBoxGuestAdditions-5.0.6/init/vboxadd; enabled)
   Active: inactive (dead)
```

Since `service` and `chkconfg` are mapped to the native systemd replacements, patching the installer to not call the init script directly and use `chkconfig vboxadd on` and `service vboxadd start` (respectively) instead will probably solve the issue.

I'll take a shot at a patch and send a pull request.  As a temporary workaround, just running `systemctl enable vboxadd` or `chkconfig vboxadd on` on the box and rebooting it will restore the mounts until the next destroy/rebuild.

**Comment by gchaix** [comment]
Of course, now that I re-read your issue, I wonder if it really is the same issue ...

**Comment by fnordfish** [comment]
Version 0.11.0 has some updates regarding the discovery of `vboxadd`. Can you please check if an update solves your issue.

**Comment by jeffsheltren** [comment]
Running 0.11.0 here and the vboxadd service(s) still aren't being properly added to systemd startup.
