### ISSUE TITLE
Future-proof auto dependency handling

### ISSUE THREAD

**Issue by evrial** [dotless-de/vagrant-vbguest#159]
Today I've upgraded to Vagrant 1.7.3 and VirtualBox 5.0 and now my VMs refusing to mount. This problem is very common and waste so much time.
I think we should make plugin future-proof and handle it for user automatically pull package list from OS repo, install/upgrade linux headers, dkms, gcc, etc.

`apt-get update && apt-get install -y linux-headers-generic > /dev/null`
`yum install -y yum-plugin-fastestmirror && yum update -y && yum install -y kernel-devel dkms build-essential`

smth like that. What do you think?

**Comment by fnordfish** [comment]
Hi @evrial ,

that's actually what all current installers (try) to do. You probably ran into some common issue where the way of guessing the correct name of the kernel herders package (matching the installed kernel version) does not work out. This issue is especially hard on centos, where older kernel header packages are removed from their repositories.

For example the [ubuntu installer](https://github.com/dotless-de/vagrant-vbguest/blob/master/lib/vagrant-vbguest/installers/debian.rb#L31) runs `apt-get install -y  linux-headers-$(uname -r)`, the [centos installer](https://github.com/dotless-de/vagrant-vbguest/blob/master/lib/vagrant-vbguest/installers/redhat.rb#L23) runs `yum install -y kernel-devel-$(uname -r)`.

I'm very open for suggestions how to make this better. (Although I still don't like any options that would require to upgrade the installed kernel)
