### ISSUE TITLE
Installation doesn't satisfy it's own dependencies

### ISSUE THREAD

**Issue by stephenreay** [dotless-de/vagrant-vbguest#184]
Running `vagrant plugin install vagrant-vaguest` results in

```
Installed the plugin 'vagrant-vbguest (0.11.0)'!
Uninstalling the 'vagrant-vbguest' plugin...
Vagrant exited after cleanup due to external interrupt.
Installing vagrant-share 1.1.5
Installing vagrant-vbguest 0.11.0
Installed the plugin 'vagrant-vbguest (0.11.0)'!
```

A subsequent call to vagrant (e.g. `vagrant status`) results in

```
Vagrant experienced a version conflict with some installed plugins!
This usually happens if you recently upgraded Vagrant. As part of the
upgrade process, some existing plugins are no longer compatible with
this version of Vagrant. The recommended way to fix this is to remove
your existing plugins and reinstall them one-by-one. To remove all
plugins:

    rm -r ~/.vagrant.d/plugins.json ~/.vagrant.d/gems

Note if you have an alternate VAGRANT_HOME environmental variable
set, the folders above will be in that directory rather than your
user's home directory.

The error message is shown below:

Bundler could not find compatible versions for gem "micromachine":
  In Gemfile:
    vagrant-vbguest (>= 0) ruby depends on
      micromachine (~> 1.1.0) ruby
Could not find gem 'micromachine (~> 1.1.0) ruby', which is required by gem 'vagrant-vbguest (>= 0) ruby', in any of the sources.
```

This is not machine specific, a client reported this error to me (while trying to resolve a vagrant/virtualbox issue - https://github.com/mitchellh/vagrant/issues/3341) and I reproduced it on my local environment by just trying to install the plugin.

**Comment by fnordfish** [comment]
Hi @stephenreay 

this is weird. `micromachine` is the only runtime "external" dependency (that is a  dependency which is not already provided by vagrant).

The dependency it stated here: https://github.com/dotless-de/vagrant-vbguest/blob/master/vagrant-vbguest.gemspec#L17 and the gem hasn't been yanked: https://rubygems.org/gems/micromachine/versions/1.1.0

As described in the error message, those kind of error happen quite often when updating vagrant. Have you tried to `rm -r ~/.vagrant.d/plugins.json ~/.vagrant.d/gems` and re-install all vagrant plugins?

(Sorry, I haven't read through al those 127 comment of the mentioned ticket)

- Robert

**Comment by stephenreay** [comment]
There is no update of vagrant happening here - this is an error immediately after attempting to install this plugin.

The person who reported it to me had no other plugins installed, but still we tried the “remove all plugins” process on his machine, then when trying to re-install, the same result.

I’m not familiar with the internals of how vagrant installs plugins, but these three lines seem pretty ominous to me:

```
Installed the plugin 'vagrant-vbguest (0.11.0)'!
Uninstalling the 'vagrant-vbguest' plugin...
Vagrant exited after cleanup due to external interrupt.
```

Why is it saying it's uninstalling immediately after saying it’s installed (and not *actually* uninstalling)? 
What is the “external interrupt” - I assumed this was Ctrl-C on the user’s part, but when I tried to install it, the same thing happened.

The only reason I referenced the other ticket is because this plugin is listed as a potential solution to the original issue the user is having.

**Comment by fnordfish** [comment]
Hi,

I'm just guessing here based on my experience with ruby projects, bundler and gems. ("gem" is common ruby packaging format for libraries and that's what a vagrant plugin comes as. "bundler" is a tool to manage ruby dependencies and is what vagrant uses to .)

What seems to happen quite often is that bundle takes pretty long figure out all dependencies - that can get pretty bad with slow/bad network. At some point either bundler itself will time-out and throw some kind of error, or a user gets impatient and just hits "Ctrl-C". So yes, that could be the "external interrupt" you where seeing.

You can try to "skip" bundler's fetching part and download the gem files manually beforehand and install those directly:

```
$ gem fetch micromachine -v 1.1.0
Fetching: micromachine-1.1.0.gem (100%)
Downloaded micromachine-1.1.0

$ gem fetch vagrant-vbguest
Fetching: vagrant-vbguest-0.11.0.gem (100%)
Downloaded vagrant-vbguest-0.11.0

$ vagrant plugin install ./micromachine-1.1.0.gem
Installing the './micromachine-1.1.0.gem' plugin. This can take a few minutes...
Installed the plugin 'micromachine (1.1.0)'!

$ vagrant plugin install ./micromachine-1.1.0.gem
Installing the './micromachine-1.1.0.gem' plugin. This can take a few minutes...
Installed the plugin 'micromachine (1.1.0)'!
```

Instead of `gem fetch` you can also download those files from:
- https://rubygems.org/downloads/vagrant-vbguest-0.11.0.gem
- https://rubygems.org/downloads/micromachine-1.1.0.gem

Another thing that could go wrong is, when another plugin you are trying to install (or have already installed) uses the same dependency on micromachine, but in a different version. I've never encountered this particular problem until now and usually bundler makes those kind of conflicts pretty clear in it's error message. I'd just wanted to mention it anyways - just in case.


Hope that helps,
Robert
