### ISSUE TITLE
Won't Build on Core OS7: "No package kernel-devel-3.10.0-327.36.3.el7.x86_64 available."

### ISSUE THREAD

**Issue by mikeflynn** [dotless-de/vagrant-vbguest#240]
It appears that the vagrant-vbguest plugin installs a very precise version of kernel-devel via the RedHat install script:

```ruby
      def dependencies
        packages = [
          'kernel-devel-`uname -r`', 'gcc', 'binutils', 'make', 'perl', 'bzip2'
        ]
        packages.join ' '
      end
```

...but that package is no longer available via Yum and without kernel-devel the plugin won't build. What is available, if you just run `yum install kernel-devel` is `kernel-devel.x86_64 0:3.10.0-514.2.2.el7`. Is there a reason the dependencies call for this specific version? Can we change it to `kernel-devel` and have it work again?

**Comment by mikeflynn** [comment]
I managed to work around this issue with the following added to my Vagrantfile:

```ruby
class CentOSFix < VagrantVbguest::Installers::Linux
  def install(opts=nil, &block)
    communicate.sudo("yum install -y gcc binutils make perl bzip2 && rpm -i ftp://195.220.108.108/linux/centos/7.2.1511/updates/x86_64/Packages/kernel-devel-3.10.0-327.36.3.el7.x86_64.rpm", opts, &block)
    super
  end
end

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # config.vm.box_check_update = false

  # Added for VagrantVbguest fix
  config.vbguest.installer = CentOSFix
 ...
````

Obviously a stop gap as it looks like that kernel-devel package had security issues and was yanked from yum, but at least I can get our Vagrant system to build in the meantime.

**Comment by carlosefr** [comment]
This happens because CentOS 7.3 has been released but the boxes haven't been updated yet. A `kernel-devel` package matching the running kernel isn't found because the repositories aren't cumulative with previous point releases.

This is a problem that perhaps should be fixed by the CentOS folks, as it breaks box pinning in the general case.

**Comment by carlosefr** [comment]
@mikeflynn I modified your workaround a bit, to make it more generic (thus handling older boxes if the `Vagrantfile` is pinning a particular version).

Now, this could be the start of a general workaround for this with only two things left to solve:\

 1. It doesn't handle point releases when no updated kernel package, has been released (this could be solved by checking if there's a package in the base repo instead);
 2. It targets the main CentOS mirror directly, which isn't nice (but other mirrors may have differing paths and I don't know how to get a list of them for a particular point release);

```
class FixGuestAdditions < VagrantVbguest::Installers::Linux
    def install(opts=nil, &block)
        communicate.sudo("yum install -y gcc binutils make perl bzip2 http://mirror.centos.org/centos/$(rpm -q --qf=%{VERSION}.%{RELEASE} centos-release | cut -d. -f-3)/updates/$(rpm -q --qf=%{ARCH} centos-release)/Packages/kernel-devel-$(uname -r).rpm", opts, &block)
        super
    end
end
```

**Comment by mikeflynn** [comment]
@carlosefr Love it! Your iteration is definitely an improvement over my "WHY WON'T THIS WORK?!" version.

**Comment by carlosefr** [comment]
An update to my previous comment that fixes the two issues left hanging: the solution below doesn't hit `mirrors.centos.org` when the package can be found in the default repos, and also handles the case of a new point release where there's no `kernel-devel` errata package yet.

I believe the proper course of action would be adding this (with the proper modifications) to the base `RedHat` installer class, since this will happen again in the future and it fixes the case of older boxes pinned in the `Vagrantfile`.

```ruby
class FixGuestAdditions < VagrantVbguest::Installers::RedHat
    def dependencies
        packages = super

        # If there's no "kernel-devel" package matching the running kernel in the
        # default repositories, then the base box we're using doesn't match the
        # latest CentOS release anymore and we have to look for it in the archives...
        if communicate.test('test -f /etc/centos-release && ! yum -q info kernel-devel-`uname -r` &>/dev/null')
            env.ui.warn("[#{vm.name}] Looking for the CentOS 'kernel-devel' package in the release archives...")
            packages.sub!('kernel-devel-`uname -r`', 'http://mirror.centos.org/centos' \
                                                     '/`grep -Po \'\b\d+\.[\d.]+\b\' /etc/centos-release`' \
                                                     '/{os,updates}/`arch`/Packages/kernel-devel-`uname -r`.rpm')
        end

        packages
    end
end
```

**Comment by RobWC** [comment]
@carlosefr you are the hero the world needs! Thanks for this work around.

**Comment by luisdavim** [comment]
Thanks @carlosefr, this was preventing me from using https://github.com/dcos/dcos-vagrant with the plugin installed.

**Comment by RogerWeihrauch** [comment]
Howdy friends of DCOS.

I am sorry for this stupid question; but, where to position above improvements in the Vagrantfile?
Does it matter where? I am not that experienced in its file's structure.
Any response will be highly appreciated.

Thanx and regards,
Roger

**Comment by RogerWeihrauch** [comment]
Howdy friends of DCOS.

Ok, seems I found carrect position in Vagrantfile. But, got now a problem on vboxadd.sh during guest addition compilation/installation/update:
----------------------------------------
..
Dependency Updated:
  glibc.x86_64 0:2.17-157.el7_3.1      glibc-common.x86_64 0:2.17-157.el7_3.1   
  libgcc.x86_64 0:4.8.5-11.el7         libgomp.x86_64 0:4.8.5-11.el7            
  perl-libs.x86_64 4:5.16.3-291.el7   

Complete!
Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 5.1.12 - guest version is 5.0.20
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.1.12 Guest Additions for Linux...........
VirtualBox Guest Additions installer
Removing installed version 5.0.20 of VirtualBox Guest Additions...
Removing existing VirtualBox non-DKMS kernel modules[  OK  ]
Copying additional installer modules ...
Installing additional modules ...
vboxadd.sh: Building Guest Additions kernel modules.
Failed to set up service vboxadd, please check the log file
/var/log/VBoxGuestAdditions.log for details.
..
-----------------------------------------------------------

What do you think on this? May there be a solution for this?


Thanx for response,
Roger

**Comment by RogerWeihrauch** [comment]
.. and again the known error on mounting via vboxsf:
------------------------------------------------------
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=501,gid=501 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
------------------------------------------------------------------

Regards,
Roger

**Comment by kzap** [comment]
update the Kernel or use `bento/centos-7.3` box
