### ISSUE TITLE
Could this be made available as a provisioner?

### ISSUE THREAD

**Issue by michaelbannister** [dotless-de/vagrant-vbguest#245]
Would it be possible to make this runnable at a specific point in the provisioning cycle? My use case is that I would like the guest additions to be installed only after I have installed xorg/X11 using a shell provisioner. As it stands, it always runs first, installs without xorg support and then I have to run it again afterwards.

**Comment by fnordfish** [comment]
Right now, vbguest injects a middleware early in order to make provisioning (like chef or puupet) using virtualbox mounts work.
So we would need to be able to disable the middleware when using the provisoner. 

The more I think about it, provisioners are way more flexible (in terms of user configuration) and it might be even a good idea to replace the current middleware implementation completely.

**Comment by loren-osborn** [comment]
I see a minor issue (and a possible solution) to making this work purely as a provisioner. Provisioners usually only run on initial box build, though they can be set to run every boot too. This would cause stale Guest Additions on boxes after a VirtualBox upgrade. (I tried to resolve this same issue previously by using a reboot provisioner, but it was rather messy at best.)

The viable solution I see is breaking the module into two parts... one runs as a boot-time middleware as it does now, but instead of updating the guest additions at that time, it only detects the if the guest additions are stale, and forces the provisioner part to execute on *THAT* boot. This way, if VirtualBox is ever upgraded, the provisioner still gets run. 

*ALSO*, if the provisioner doesn't appear in the list of registered provisioners, it can add itself as the first provisioner implicitly, to maintain close to its current behavior without requiring Vagrantfile changes. (If it *does* appear in the list, it's run order can be altered by moving it in the Vagrantfile.)

**Comment by myroad94** [comment]
For info for other people looking at the same issue, here is a good workaround: https://github.com/dotless-de/vagrant-vbguest/issues/166#issuecomment-134400002
