### ISSUE TITLE
guest additions fails with virtualbox 5.1.22

### ISSUE THREAD

**Issue by HenrikBechmann** [dotless-de/vagrant-vbguest#251]
I get 

```

Verifying archive integrity... All good.
Uncompressing VirtualBox 5.1.22 Guest Additions for Linux...........
VirtualBox Guest Additions installer
You appear to have a version of the VirtualBox Guest Additions
on your system which was installed from a different source or using a
different type of installer.  If you installed it from a package from your
Linux distribution or if it is a default part of the system then we strongly
recommend that you cancel this installation and remove it properly before
installing this version.  If this is simply an older or a damaged
installation you may safely proceed.

Do you wish to continue anyway? [yes or no]

Cancelling installation.

```
I've tried all kinds of things, but can't get past it. Any tips?

**Comment by HenrikBechmann** [comment]
For virtualbox 5.1.20 I had to do

```
sudo ln -sf /opt/VBoxGuestAdditions-5.1.20/lib/VBoxGuestAdditions/mount.vboxsf /sbin/mount.vboxsf

```

to get things working, and now when I revert to 5.1.20 I get the same block as above message.

I wonder if that 'fix' (found on stackexchange) caused the problem?

**Comment by HenrikBechmann** [comment]
Yeah I think that was it. 

The failed install attempt left a couple of *vbox* symlinks (without source files) in /sbin
- I removed them
- installed vb 5.1.20
- rebooted mac
- ran vagrant vbguest --do install
- vagrant ssh
- cd /opt/VBGuestAdditions-5.1.20 
- ran ./uninstall.sh (to get a clean uninstall)
- shut down vm
- rebooted mac
- upgraded to vb 5.1.22
- vagrant up then triggered install of correct guest additions

bah

**Comment by HenrikBechmann** [comment]
short version is probably (if you 'fixed' previous install of 5.1.20)

- first uninstall guest additions
- clean out any broken symlinks like *vbox* in /sbin
- then do upgrade

**Comment by rulatir** [comment]
Could you please post the exact commands for this? I am being bitten by this issue and I would very much like to avoid spending two days on Google trying to figure out what exact commands those three bullet points map to. In particular, "then do upgrade" is completely vague: I have no idea what I should upgrade in that step, other than that you probably don't mean host's graphic card drivers ;) Is it virtualbox? Vagrant? This plugin? Guest additions package on host? Guest additions package on vm? Guest OS?

**Comment by rulatir** [comment]
I cannot follow @HenrikBechmann 's self-solution above. I request reopening this issue.

**Comment by HenrikBechmann** [comment]
See [here](https://github.com/dotless-de/vagrant-vbguest/issues/252#issuecomment-298296965) for more details

**Comment by cameronkerrnz** [comment]
I had a similar issue upgrading from 5.1.20 to 5.1.22, and in my case it seems (looking with strace) that the message may have been occurring due to the lack of the file /opt/VBoxGuestAdditions-5.1.22/uninstall.sh

Previously, there were a number of /opt/VBoxGuestAdditions-* folders, which evidently got cleaned up.

Lacking an uninstall.sh script, I eventually found out that I could do the following:

/path/to/VBOXADDITIONS_5.1.22_115126/VBoxLinuxAdditions.run -- uninstall

(note: there are two arguments there; the "--" is separate from the "uninstall". This is because the "--" serves to pass the "uninstall" as an argument to the installer. I happened to discover this when when I passed "--help" to the VBoxLinuxAdditions.run script, and then decided that "-- --help" might be interesting. Lo and behold it turns out that it has an "uninstall" flag.)

I did _not_ have to undo the fix mount.vboxsf

Short story, after uninstalling this way, the installer works (and now there is an uninstall.sh script). Rebooting the VM everything (X11, Clipboard sharing, Shared folders) seems to be working well.

(Note: I wasn't doing this using vagrant-vbguest at the time)

PS. This was on RHEL 7.3, VirtualBox 5.1.22 (upgraded from 5.1.20)

Hope this helps.
(really wish upgrading VirtualBox was a less painful process).

Cheers,
Cameron

**Comment by lmayorga1980** [comment]
Added a reference to another project since VirtualBox Guest for Windows is giving me problems

**Comment by c-sonntag** [comment]
Maybe you can go to see my issue at this link : https://github.com/dotless-de/vagrant-vbguest/issues/252#issuecomment-331585965

**Comment by marxenegls** [comment]
you'd do apt-get purge virtualbox-guest-utils only if you installed them through apt, i presume, yes there's an Ubuntu repo available , otherwise if manually installed , they'd be located in /opt dir, there's an unistall script. 
 $ sudo ./uninstall.sh from within dir ..
... then insert the new guestadditions .iso that came with the upgraded VBox with
$: sudo mount /dev/cdrom /mnt 
$: cd /mnt 
$: sudo ./VboxLinuxAdditions.run

**Comment by Arnold1** [comment]
get a similar issue:
Host OS: Mac OSX
Guest OS: Debian 7.0
VirtualBox: 5.1.14 r112924 (Qt5.6.2)

is there something wrong now? if so, how to fix it?
```
arnold@debian-VirtualBox:~$ mount /media/cdrom
mount: block device /dev/sr0 is write-protected, mounting read-only
 
arnold@debian-VirtualBox:~$ sudo sh /media/cdrom/VBoxLinuxAdditions.run
[sudo] password for arnold: 
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.1.14 Guest Additions for Linux...........
VirtualBox Guest Additions installer
You appear to have a version of the VirtualBox Guest Additions
on your system which was installed from a different source or using a
different type of installer.  If you installed it from a package from your
Linux distribution or if it is a default part of the system then we strongly
recommend that you cancel this installation and remove it properly before
installing this version.  If this is simply an older or a damaged
installation you may safely proceed.
 
Do you wish to continue anyway? [yes or no]
yes
Copying additional installer modules ...
Installing additional modules ...
vboxadd.sh: Building Guest Additions kernel modules.                              
vboxadd.sh: You should restart your guest to make sure the new modules are actually used.                                                                           
vboxadd.sh: Starting the VirtualBox Guest Additions.                              
 
You may need to restart the Window System (or just restart the guest system)      
to enable the Guest Additions.
 
This system appears to be running a version of Mesa with a known problem
which will prevent VirtualBox 3D pass-through from working.  See
  https://b...content-available-to-author-only...p.org/show_bug.cgi?id=26663
The following, run as root should fix this, though you will have to run it
again if the system version of Mesa is updated:
  strip -R .note.ABI-tag /usr/lib/x86_64-linux-gnu/libGL.so.1
  ldconfig
arnold@debian-VirtualBox:~$
```

**Comment by richard-scott** [comment]
Maybe try updating VirtualBox if you are still running 5.1.x

**Comment by Arnold1** [comment]
can i update virtual box without snapshotting my debian image?
