### ISSUE TITLE
Only update/install guest additions on basebox(es) instead of every VM

### ISSUE THREAD

**Issue by TjWallas** [dotless-de/vagrant-vbguest#296]
Installing and updating the Vbox guest additions on every VM defined in a multi-machine Vagrantfile takes a very long time. Wouldn't it be more efficient to update & install the guest additions only on the common base box(es) instead?

This way, every spawned VM which uses those updated basebox(es) inherently has the updated Vbox guest additions. 

The rough sketch of the algorithm, could be as follows:
1. Instantiate a new instance of the base box
2. Update guest additions inside it
3. Locally repackage the result as the new basebox. 
4. Continue instantiating VMs from the above resultant basebox.

In cases where multiple VMs share a basebox, I hypothesize that this will be many-fold faster.

Edit: I realize that the above applies to only new VMs and not existing ones. The existing code could still be applied so as to update existing VMs. Maybe my proposal here could be available as a sub-command :)

**Comment by dragetd** [comment]
3. is the issue here. You would need to re-package the whole basebox, which is a very different thing to running scripts inside the guest.

If you spawn many VMs of the same basebox, it might be worth it manually updating it. Repackaging would be kind of unexpected with this plugin. I suggest taking a look at 'Hashicorp Packer' and roll your own boxes - for more complicated setups this allows a lot more flexebility. :-)
