### ISSUE TITLE
VBox guest editions fails on CentOS 7 - kernel-devel-3.10.0-862.14.4.el7.x86_64 not found

### ISSUE THREAD

**Issue by spstarr** [dotless-de/vagrant-vbguest#311]
It looks like VirtualBox 5.2.22 broke things again...

Could we include kernel-devel in the vagrant box so the kernel drivers can be compiled if not already provided by the guest editions?

Wouldn't this keep things in sync so no matter what running kernel, the header/devel RPMs for the running matching kernel always are in the image?

Thanks
Shawn.

**Comment by darthgogy** [comment]
The same on VirtualBox 5.2.20.
centos/7 Vagrant box v1809.01
kernel-devel-3.10.0-957.1.3.el7.x86_64 was installed instead of kernel-devel-3.10.0-862.14.4.el7.x86_64.

```
. . .
[default] No installation found.
Loaded plugins: fastestmirror
Determining fastest mirrors
 * base: mirror.mirohost.net
 * extras: mirror.mirohost.net
 * updates: mirror.mirohost.net
No package kernel-devel-3.10.0-862.14.4.el7.x86_64 available.
. . .
  Installing : kernel-devel-3.10.0-957.1.3.el7.x86_64                     40/45
. . .
Copy iso file C:\Program Files\Oracle\VirtualBox\VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Mounting Virtualbox Guest Additions ISO to: /mnt
mount: /dev/loop0 is write-protected, mounting read-only
Installing Virtualbox Guest Additions 5.2.20 - guest version is unknown
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.2.20 Guest Additions for Linux........
VirtualBox Guest Additions installer
Copying additional installer modules ...
Installing additional modules ...
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.  This may take a while.

This system is currently not set up to build kernel modules.
Please install the Linux kernel "header" files matching the current kernel
for adding new hardware support to the system.
The distribution packages containing the headers are probably:
    kernel-devel kernel-devel-3.10.0-862.14.4.el7.x86_64
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: Building the VirtualBox Guest Additions kernel modules.  This may take a while.

This system is currently not set up to build kernel modules.
Please install the Linux kernel "header" files matching the current kernel
for adding new hardware support to the system.
The distribution packages containing the headers are probably:
    kernel-devel kernel-devel-3.10.0-862.14.4.el7.x86_64
An error occurred during installation of VirtualBox Guest Additions 5.2.20. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Redirecting to /bin/systemctl start vboxadd.service
Job for vboxadd.service failed because the control process exited with error code. See "systemctl status vboxadd.service" and "journalctl -xe" for details.
Unmounting Virtualbox Guest Additions ISO from: /mnt
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Mounting shared folders...
    default: /vagrant => C:/vms/centos7-test
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

**Comment by jaredanderson1** [comment]
> The same on VirtualBox 5.2.20 and 5.2.18.
> centos/7 Vagrant box v1809.01
> kernel-devel-3.10.0-957.1.3.el7.x86_64 was installed instead of kernel-devel-3.10.0-862.14.4.el7.x86_64.

Indeed, same issue here. I got around this by updating the kernel to 3.10.0-957, but this is just a temporary workaround, must be a better way, e.g.
- vagrant up ... until it fails as above
- vagrant ssh
- sudo yum -y update kernel
- exit
- vagrant reload --provision

**Comment by tjsheppard** [comment]
Similar issue but your fix worked! Thank you @jaredanderson1

**Comment by CorbMax** [comment]
> > The same on VirtualBox 5.2.20 and 5.2.18.
> > centos/7 Vagrant box v1809.01
> > kernel-devel-3.10.0-957.1.3.el7.x86_64 was installed instead of kernel-devel-3.10.0-862.14.4.el7.x86_64.
> 
> Indeed, same issue here. I got around this by updating the kernel to 3.10.0-957, but this is just a temporary workaround, must be a better way, e.g.
> 
>     * vagrant up ... until it fails as above
> 
>     * vagrant ssh
> 
>     * sudo yum -y update kernel
> 
>     * exit
> 
>     * vagrant reload --provision

Same issue and same workaroud here.
It worked

**Comment by nighthacker** [comment]
Same problem here. IMHO problem with box not with plugin itself.

**Comment by jaredanderson1** [comment]
On second thoughts, is the problem that the plugin installs the latest version of kernel-devel instead of the version that matches the kernel on the box?

If I provision with these settings:
config.vm.box = "centos/7"
	
config.vm.box_version = "1809.01"
config.vbguest.auto_update = false

I end up with:

kernel.x86_64                    3.10.0-862.14.4.el7            @koji-override-1
kernel-tools.x86_64              3.10.0-862.14.4.el7            @koji-override-1
kernel-tools-libs.x86_64         3.10.0-862.14.4.el7            @koji-override-1

If I remove config.vbguest.auto_update = false, I get:

kernel.x86_64 3.10.0-862.14.4.el7 @koji-override-1
kernel-devel.x86_64 3.10.0-957.1.3.el7 @updates
kernel-headers.x86_64 3.10.0-957.1.3.el7 @updates
kernel-tools.x86_64 3.10.0-862.14.4.el7 @koji-override-1
kernel-tools-libs.x86_64 3.10.0-862.14.4.el7 @koji-override-1

**Comment by fnordfish** [comment]
Hi all, CentOS and kernel headers are a long-time pain and every once in a while it bubbles up. There have been made various attempts on getting a solution that survives different CentOS and/or VirtualBox upgrades.

Please have a look over at those old issues #223, #231 
There seems also be some new work in #314

I'm closing this issue. Please move discussions into eg. the [Gitter Chat](https://gitter.im/dotless-de/vagrant-vbguest?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by fnordfish** [comment]
Small update, there's a brand new beta version (0.17.0beta2) available with the new CentOS installer of #314

**Comment by ccan06** [comment]
https://forums.virtualbox.org/posting.php?mode=reply&f=3&t=91563

You can find possible problems and their answers below
https://www.youtube.com/watch?v=NHGXkuzUBzE

Problems and solutions of:
1-Kernel headers not found for target kernel 4.18.0-147
2-Please install the gcc make perl packages from your distribution
3-Cannot generate ORC metadata for CONFIG_UNWINDER_ORC=y; installing elfutils-libelf-devel

Clear Installation...

**Comment by ralf-k-a** [comment]
The root of this problem is the management of updates for CentOS: When CentOS publishes a new release, support for the previous release is removed from the mirror servers. For example CentOS 7.8. support disappeared on 2020-11-17, when CentOS 7.9 was published. See the timestamps in http://mirror.centos.org/centos. The current and the previous version have the same timestamp and in the directory of the previous version you'll find a readme file telling what has happened.

Since the publishing of vagrant box images for CentOS are not in sync with the publishing of new CentOS releases, you will always fail with provisioning, when this happens. For example on 2020-11-24 there is only the 7.8 box available (which fails to work) bu not a 7.9 one. 

The best way to make it work again is to add the vault archive for the version the box is based on to the yum configuration. To do so, you have to modify /etc/yum.repos.d/CentOS-Vault.repo.

For CentOS 7.8 I have attached a suitable configuration in [CentOS-Vault_7.8_entries.txt](https://github.com/dotless-de/vagrant-vbguest/files/5591864/CentOS-Vault_7.8_entries.txt). To add the configuration the I did

- `vagrant up` (which fails with a missing kernel-devel RPM)
- login with `vagrant ssh`
- edit the file /etc/yum.repos.d/CentOS-Vault.repo as root
- exit the vm

Then I run`vagrant reload --provision` to continue provisioning.

To automate this you can add the contents of 
[Vagrantfile_snippet.txt](https://github.com/dotless-de/vagrant-vbguest/files/5592317/Vagrantfile_snippet.txt)
to your `Vargrantfile`. The snippet shows you the fix for CentOS 7.8. It requires you to have installed version 26 or newer of the vagrant-vbguest plugin.

Alternatively you cat update the kernel as described in one of the comments above and restart. However his cannot be automated since it would require a reboot after the kernel update. I could not make this work.

Or you can create a new CentOS box from the official one after applying the fix and use this box instead of the original CentOS/7 box. See `vagrant box repackage` on https://www.vagrantup.com/docs/cli/box for how to create new boxes for vagrant.

**Comment by ralf-k-a** [comment]
The problem is also reported to CentOS: https://bugs.centos.org/view.php?id=17884

**Comment by vinieq** [comment]
this is what suits me the most:

```
Vagrant.configure("2") do |config|
  config.vm.define "my_cent_os_box" do |c|
    c.box = "centos/8"
    c.vbguest.installer_options = { allow_kernel_upgrade: true }
  end
end
```

https://github.com/dotless-de/vagrant-vbguest
