### ISSUE TITLE
Please document box requirements for vagrant-vbguest

### ISSUE THREAD

**Issue by attila123** [dotless-de/vagrant-vbguest#344]
I have an issue with generic/fedora30 virtualbox box + vagrant-vbguest: it does not find some 'start' and 'setup' commands. I created an issue here: https://github.com/lavabit/robox/issues/65 (see log there).
I quickly checked the readme of this project and did not find any guidelines how box developers should make sure that their box is compatible with this plugin.
Please create the documentation for this.

**Comment by attila123** [comment]
Another issue that it is not obvious for the end users (who may have installed this plugin months or years ago) that the log messages are related to this vagrant-vbguest plugin. I am wondering whether it is vagrant level issue... Is this a vagrant level problem?
The log messages I mean (copying from the linked issue for your convenience):
```
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   6.0.0
VBoxService inside the vm claims: 6.0.8
Going on, assuming VBoxService is correct...
[default] GuestAdditions seems to be installed (6.0.8) correctly, but not running.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   6.0.0
VBoxService inside the vm claims: 6.0.8
Going on, assuming VBoxService is correct...
bash: line 4: start: command not found
bash: line 4: start: command not found
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   6.0.0
VBoxService inside the vm claims: 6.0.8
Going on, assuming VBoxService is correct...
bash: line 4: setup: command not found
==> default: Checking for guest additions in VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

 setup

Stdout from the command:



Stderr from the command:

bash: line 4: setup: command not found

```

**Comment by fnordfish** [comment]
Hi, vbguest does not put any requirements on the box (although it would be nice if it would not have any system-package version of the Guest Additions installed)
In your particular case, vbguest was not able to find the `vboxadd` tool, which should be provided by an virtualbox guest additions installation. We ended up in this state, because vbguest found that VirtualBox Guest Addtions are installed, but not running, so it tried to rebuild the using `vboxadd setup` (this way of rebuilding might also be problematic depending on the version of VirtualBox, put that's a different issue)
After a short look into [robox](https://github.com/lavabit/robox/blob/master/scripts/fedora30/virtualbox.sh) it might be the packaged guest additions that made vbguest tip over.

So maybe we should state the absence of distribution packaged guest additions as a (soft?) requirement.

**Comment by attila123** [comment]
Hmm, maybe in that case it would be nice to have some clean log e.g. "error: vagrant-vbguest plugin failed to execute 'vboxadd' in the VM" or something like that.
I was under the impression that it wants to run some magic 'start' and 'setup' commands.
Yes I think something like this would be nice:
"Distribution packaged guest additions installation is discouraged:
- it may not contain relevant tools e.g. vboxadd required by this plugin
- overwriting distribution packaged guest additions with an updated version may create confusion and mess in the VM"
(feel free to improve it, English is not my mother tongue :) )
