### ISSUE TITLE
`find_tool` fails silently when `vboxadd` could not be found

### ISSUE THREAD

**Issue by fnordfish** [dotless-de/vagrant-vbguest#345]
Originally reported in #344

**Comment by dcermak** [comment]
I have been hit by exactly this problem just now, but with a very weird twist:
- the `dcermak/Leap-15.1.x86_64` box will abort being started on a machine running Leap 15.1 with:
``` ShellSession
==> default: Machine booted and ready!
[default] GuestAdditions seems to be installed (6.0.12) correctly, but not running.
service: no such service vboxadd
Warning: vboxadd-service.service changed on disk. Run 'systemctl daemon-reload' to reload units.
bash: line 4: setup: command not found
==> default: Checking for guest additions in VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

 setup

Stdout from the command:



Stderr from the command:

bash: line 4: setup: command not found

```
- The same vagrant box will happily start up on a machine running Tumbleweed! I suspect that this is due to the vagrant guest additions inside the box being at 6.0.12 and those of the host at 6.0.14.

Is there something that I (as the box author) can do to prevent this from happening?
