### ISSUE TITLE
Cannot install kernel-devel-3.10.0-957.12.2.el7.x86_64

### ISSUE THREAD

**Issue by openface** [dotless-de/vagrant-vbguest#349]
Using latest Centos/7 vagrant box:

```
  config.vm.box = "centos/7"
  config.vm.box_version = "1905.1"
```

And latest vagrant-vbguest:

```
vagrant-vbguest (0.19.0, global)
```

Fails to install kernel-devel-3.10.0-957.12.2.el7.x86_64 from CentOS Vault:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum install -y kernel-devel-`uname -r` --enablerepo=C*-base --enablerepo=C*-updates

Stdout from the command:

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.metrocast.net
 * extras: repos-tx.psychz.net
 * updates: mirror.metrocast.net


Stderr from the command:

http://vault.centos.org/7.6.1810/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
```

Seems this was working fine until sometime yesterday around 5pm.  :(

**Comment by Blekely** [comment]
Had the same issue.  Its not a vbguest issue.  Has something to do with CentOS's vault not being up to date due to a new release.  Should correct itself in a week or so.

I was able to get past this by updating file `/etc/yum.repos.d/CentOS-Vault.repo`
and changing the last 5 repo's `baseurl`
`http://vault.centos.org/7.6.1810/...` -> `http://mirror.centos.org/centos/7.6.1810/...`

So, to start do a `vagrant up`, once you get the error, `vagrant ssh` and make the above change.
Then `vagrant reload` and that should complete the usual process.

**Comment by Ecsy** [comment]
The issue with the mirror is one thing, but after fixing it:
```bash
vagrant]# uname -r
3.10.0-957.12.2.el7.x86_64
vagrant]# yum --showduplicates list kernel-devel-3.10.0
Available Packages
kernel-devel.x86_64                                                                               3.10.0-1062.el7                                                                                   base
kernel-devel.x86_64                                                                               3.10.0-1062.1.1.el7                                                                               updates
```
The required version for kernel-devel is not available, only a newer version.

**Comment by Ecsy** [comment]
vault.centos.org is fixed. Everything is back to normal. I think this issue is closable.

**Comment by openface** [comment]
Confirmed, thanks!
