### ISSUE TITLE
0.25.0 doesn't reboot after gust additions is installed.

### ISSUE THREAD

**Issue by lukechilds** [dotless-de/vagrant-vbguest#387]
When using the latest version of this plugin (0.25.0) after installing guest additions the VM does not get rebooted so the latest version is not used and mounting the `/vagrant` volume fails. This causes the VM to be destroyed and you can never progress beyond this point.

Installing version 0.24.0 of this plugin resolves the issue. The VM is rebooted after guest additions is installed and everything works as expected.

**Comment by henning** [comment]
Hi, I have the same issue with 0.26

The guest I am observing it with is debian/buster64 - it used to work before, but since i cannot tell exactly when I did a fresh install the last time with this develoment system, i can't tell exactly what the last versions have been with which it worked. 
Must be sometime around the previous half year or so, as I got a new machine in spring.

Can happily provide more logs and output if that helps @fnordfish

**Comment by lukechilds** [comment]
@fnordfish My issue was also with debian/buster64.

You can see the exact environment here: https://github.com/getumbrel/umbrel-dev/blob/master/Vagrantfile

@henning as a temporary workaround run the following in the Vagrant dir:

```
vagrant plugin uninstall vagrant-vbguest && vagrant plugin install --local vagrant-vbguest --plugin-version=0.24.0
```

**Comment by fnordfish** [comment]
I'm not sure you two have the same issue - anyways, there's some funny business going on with newer vagrant, vbguest and buster.

@henning Somehow the middleware of vbguest stopped working with vagrant 2.2.11 - I'm investigating and preparing an issue over at vagrant.

@lukechilds 
v0.25, changed on how vbguest detects running guest additions ([GH-347], [GH-376], [GH-377]).
I think, that the old way was wrong and mistakenly did not detect the kernel extension, which had the "positive" effect of causing a reboot. Now, with the fixed detection somehow the kernel extensions will be found but are not functional.
Newer VirtualBox guest addiotions seem to print this after installation:
```
VirtualBox Guest Additions: To build modules for other installed kernels, run
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup <version>
VirtualBox Guest Additions: or
VirtualBox Guest Additions:   /sbin/rcvboxadd quicksetup all
VirtualBox Guest Additions: Building the modules for kernel
```

Can you try using this new 0.26 feature:

```
Vagrant.configure("2") do |config|
  config.vm.define "my_buster_box" do |c|
    c.vbguest.installer_hooks[:after_install] = ["/sbin/rcvboxadd quicksetup all"]
  end
end

**Comment by fnordfish** [comment]
Sorry, the `/sbin/rcvboxadd quicksetup all` thing does not work (yet)

**Comment by henning** [comment]
@lukechilds cool thanks! I thought about doing that downgrade but had no time, and so you spared me to find out the exact commands ;)

I get some strange error message when running these commands, but anyway the plugin is there, at the working version, and the VM install process works perfect without the need of manual reloads after that! 

Here's that output that I dont understand, because it happens after the uninstall of 0.26, so vagrant shouldnt know about that version anymore,  but that anyway does not seem to interfere with the functionality:

```
$ vagrant plugin install vagrant-vbguest --plugin-version=0.24.0
Installing the 'vagrant-vbguest --version '0.24.0'' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

Gem 'vagrant-vbguest-0.26.0' is not installed in directory /home/henning/.vagrant.d/gems/2.7.1
```
Actually the mentioned gems dir contains also a directory with 0.26 code, so this message is wrong at least twice.

No action needed, i just post it as a note that others with the same problem know they can work despite this error...

**Comment by henning** [comment]
@fnordfish I am at version 2.2.9 as is delivered with Ubuntu 20.10, and the downgrade solution Luke provided here worked just fine for now! 

Let me know when you need help testing the fix for this issue, I am happy to help.

**Comment by HeikkiYlipaavalniemi** [comment]
We are also running an old CentOS 7 based box geerlingguy/centos7.

The same problem happened there still with 0.27.0 version of vbguest but downgrading to 0.24.0 fixed the issue there.
