### ISSUE TITLE
Guest Additions and VM issue about shared folders

### ISSUE THREAD

**Issue by swatch-ranjit** [dotless-de/vagrant-vbguest#390]
I updated my environement so I have the following configuration.

- vagrant box : generic/ubuntu1804 (virtualbox, 3.1.2)
- vagrant version : 2.2.13
- vagrant-vbguest : 0.26.0
- vagrant-bindfs : 1.1.8
- vagrant-hostsupdater : 1.1.1.160
- vagrant-share : 1.1.11
- vagrant-winnfsd : 1.4.0

While doing a **vagrant up**,  Im facing a **Guest Additions** issue:

_The guest additions on this VM do not match the installed version of
VirtualBox! In most cases this is fine, but in rare cases it can
cause things such as shared folders to not work properly. If you see
shared folder errors, please update the guest additions within the
virtual machine and reload your VM._

As a consequence, it doesn't bind my folder from my Windows 10 to my Ubuntu. In the code below, only the first line is working:

```
config.vm.synced_folder ".", "/var/www/test__nfs", type: "nfs"
config.bindfs.bind_folder "/var/www/test__nfs", "/var/www/test", perms: "u=rwX:g=rwX:o=rX"
```

If I do `ls /var/www/` I can see **test__nfs** but not **test**.

I could align the version of the Guest Additions and the VM with:

`vagrant vbguest --auto-reboot`

I also updated the kernel and restarted Ubuntu:
`sudo apt upgrade
sudo shutdown now`

Im still getting this issue..

I also reinstalled and reinstalled everything.

Does someone know something?

**Comment by fnordfish** [comment]
Hi @swatch-ranjit 

you're writing that,

> In the code below, only the first line is working [`config.vm.synced_folder ".", "/var/www/test__nfs", type: "nfs"
`]
> I could align the version of the Guest Additions and the VM with

If virtualbox is able to mount you windows filesystem, so that inside our box you can `ls /var/www/test__nfs` and see what you are supposed to see, everything related to guest additions is fine.

My guess is, that you run into permission issues with bindfs in `/var/www`.

If indeed your "synced_folder" share is working, I would like to ask you to take your question to the vagrant-bindfs project and/or to the vagrant mailing list.

**Comment by swatch-ranjit** [comment]
Thanks for the reply.

So I opened exactly the same issue here: https://github.com/gael-ian/vagrant-bindfs/issues/94

**Comment by fnordfish** [comment]
Good luck
